version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: eBKIUm4YxcrbL3oVC/ZCBUA/inEu+7OMbKpgftpOc18ievKNwH8UAUB2t4w+89Xv
  BUILD_BOT_PASSWORD:
    secure: nRnlm4SD3Htof+YIoW7URXirI8vKtVrZX24Cou4mtfjwvj1OZkotbS5jogxhf06x
  APPVEYOR_YML_DISABLE_PS_LINUX: true
build_script:
- ps: .\build.ps1 --target=Publish
- sh: ./build.sh --target=Package
test: off
