version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: rFsvWqQyNMq89Bm2UUBbv1hw7EqmUtphBMKqfwfDHtwIKnknms5vcIay4XYFEXea
  BUILD_BOT_PASSWORD:
    secure: nRnlm4SD3Htof+YIoW7URXirI8vKtVrZX24Cou4mtfjwvj1OZkotbS5jogxhf06x
build_script:
- cmd: .\build.cmd publish "--trigger=%APPVEYOR_REPO_TAG_NAME%" "--build-number=%APPVEYOR_BUILD_NUMBER%"
- sh: ./build.sh package
test: off
