version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: QEn16fxymoBroWnkHAsN94ARrAA8tX/L48Ue90x3zfxN0YMgwczJEVtTs/71HR5A
  BUILD_BOT_PASSWORD:
    secure: nRnlm4SD3Htof+YIoW7URXirI8vKtVrZX24Cou4mtfjwvj1OZkotbS5jogxhf06x
  APPVEYOR_YML_DISABLE_PS_LINUX: true
build_script:
- ps: .\build.ps1 --target=Publish
- sh: ./build.sh --target=Package
test: off
