version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: rFsvWqQyNMq89Bm2UUBbv1hw7EqmUtphBMKqfwfDHtwIKnknms5vcIay4XYFEXea
  BUILD_BOT_PASSWORD:
    secure: nRnlm4SD3Htof+YIoW7URXirI8vKtVrZX24Cou4mtfjwvj1OZkotbS5jogxhf06x
build_script:
- cmd: if %APPVEYOR_REPO_BRANCH% neq master .\build.cmd package
- cmd: if %APPVEYOR_REPO_BRANCH% equ master if defined APPVEYOR_PULL_REQUEST_NUMBER .\build.cmd package
- cmd: if %APPVEYOR_REPO_BRANCH% equ master if not defined APPVEYOR_PULL_REQUEST_NUMBER .\build.cmd publish --trigger=publish-all --build-number=%APPVEYOR_BUILD_NUMBER%
- sh: ./build.sh package
test: off
