version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: ui2NHCkD1RaeInP9garBAG67yxHp78AykDTSKGZcWX25GehDjWz/K8w24QkHItgz
  BUILD_BOT_PASSWORD:
    secure: nRnlm4SD3Htof+YIoW7URXirI8vKtVrZX24Cou4mtfjwvj1OZkotbS5jogxhf06x
build_script:
- cmd: .\build.cmd publish "--trigger=%APPVEYOR_REPO_TAG_NAME%" "--branch=%APPVEYOR_REPO_BRANCH%" "--nuget-api-key=%NUGET_API_KEY%"
- sh: ./build.sh package
test: off
artifacts:
- path: 'release\*.nupkg'
