using System.Linq;
using Shouldly;
using Xunit;

namespace Facility.Definition.UnitTests.FsdTests
{
	public sealed class DtoTests
	{
		[Fact]
		public void OneMinimalDto()
		{
			var service = TestUtility.ParseTestApi("service TestApi { data One { } }");

			var dto = service.Dtos.Single();
			dto.Name.ShouldBe("One");
			dto.Attributes.Count.ShouldBe(0);
			dto.Fields.Count.ShouldBe(0);
			dto.Summary.ShouldBe("");
			dto.Remarks.Count.ShouldBe(0);
			service.Dtos.FirstOrDefault(x => x.Name == "One").ShouldBe(dto);

			TestUtility.GenerateFsd(service).ShouldBe(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"service TestApi",
				"{",
				"\tdata One",
				"\t{",
				"\t}",
				"}",
				"",
			});
		}

		[Fact]
		public void TwoDtosSameName()
		{
			TestUtility.ParseInvalidTestApi("service TestApi { data One {} data One {} }")
				.Message.ShouldBe("TestApi.fsd(1,31): Duplicate service member: One");
		}
	}
}
