using System.Linq;
using NUnit.Framework;
using Shouldly;

namespace Facility.Definition.UnitTests.FsdTests
{
	public sealed class EnumTests
	{
		[Test]
		public void OneMinimalEnum()
		{
			var service = TestUtility.ParseTestApi("service TestApi { enum One { X } }");

			var enumInfo = service.Enums.Single();
			enumInfo.Name.ShouldBe("One");
			enumInfo.Attributes.Count.ShouldBe(0);
			enumInfo.Summary.ShouldBe("");
			enumInfo.Remarks.Count.ShouldBe(0);
			var enumValue = enumInfo.Values.Single();
			enumValue.Name.ShouldBe("X");
			enumValue.Attributes.Count.ShouldBe(0);
			enumValue.Summary.ShouldBe("");
			service.Enums.FirstOrDefault(x => x.Name == "One").ShouldBe(enumInfo);

			TestUtility.GenerateFsd(service).ShouldBe(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"service TestApi",
				"{",
				"\tenum One",
				"\t{",
				"\t\tX,",
				"\t}",
				"}",
				"",
			});
		}
	}
}
