using System.Linq;
using NUnit.Framework;
using Shouldly;

namespace Facility.Definition.UnitTests.FsdTests
{
	public sealed class ErrorSetTests
	{
		[Test]
		public void OneMinimalErrorSet()
		{
			var service = TestUtility.ParseTestApi("service TestApi { errors One { X } }");

			var errorSet = service.ErrorSets.Single();
			errorSet.Name.ShouldBe("One");
			errorSet.Attributes.Count.ShouldBe(0);
			errorSet.Summary.ShouldBe("");
			errorSet.Remarks.Count.ShouldBe(0);
			var error = errorSet.Errors.Single();
			error.Name.ShouldBe("X");
			error.Attributes.Count.ShouldBe(0);
			error.Summary.ShouldBe("");

			TestUtility.GenerateFsd(service).ShouldBe(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"service TestApi",
				"{",
				"\terrors One",
				"\t{",
				"\t\tX,",
				"\t}",
				"}",
				"",
			});
		}
	}
}
