using System.Linq;
using NUnit.Framework;
using Shouldly;

namespace Facility.Definition.UnitTests.FsdTests
{
	public sealed class MethodTests
	{
		[Test]
		public void OneMinimalMethod()
		{
			var service = TestUtility.ParseTestApi("service TestApi { method do {}: {} }");

			var method = service.Methods.Single();
			method.Name.ShouldBe("do");
			method.Attributes.Count.ShouldBe(0);
			method.Summary.ShouldBe("");
			method.Remarks.Count.ShouldBe(0);
			method.RequestFields.Count.ShouldBe(0);
			method.ResponseFields.Count.ShouldBe(0);

			TestUtility.GenerateFsd(service).ShouldBe(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"service TestApi",
				"{",
				"\tmethod do",
				"\t{",
				"\t}:",
				"\t{",
				"\t}",
				"}",
				"",
			});
		}
	}
}
