namespace Facility.Definition.CodeGen
{
	/// <summary>
	/// Helper methods for generating code.
	/// </summary>
	public static class CodeGenUtility
	{
		/// <summary>
		/// Gets the standard "do not edit" comment for generated code.
		/// </summary>
		public static string GetCodeGenComment(string generatorName)
		{
			return "DO NOT EDIT: generated by " + generatorName;
		}

		/// <summary>
		/// Capitalizes the specified string.
		/// </summary>
		public static string Capitalize(string value)
		{
			return value.Length == 0 ? "" : value.Substring(0, 1).ToUpperInvariant() + value.Substring(1);
		}
	}
}
