using System.Linq;
using FluentAssertions;
using NUnit.Framework;

namespace Facility.Definition.UnitTests.Fsd
{
	public sealed class ServiceTests
	{
		[Test]
		public void EmptyServiceDefinition()
		{
			var service = TestUtility.ParseTestApi("service TestApi{}");

			service.Name.Should().Be("TestApi");
			service.Attributes.Count.Should().Be(0);
			service.ErrorSets.Count.Should().Be(0);
			service.Enums.Count.Should().Be(0);
			service.Dtos.Count.Should().Be(0);
			service.Methods.Count.Should().Be(0);
			service.Summary.Should().Be("");
			service.Remarks.Count.Should().Be(0);

			TestUtility.GenerateFsd(service).Should().Equal(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"service TestApi",
				"{",
				"}",
				"",
			});
		}

		[Test]
		public void EmptyServiceDefinitionWithWhitespace()
		{
			var service = TestUtility.ParseTestApi(" \r\n\t service \r\n\t TestApi \r\n\t { \r\n\t } \r\n\t ");

			service.Name.Should().Be("TestApi");

			TestUtility.GenerateFsd(service).Should().Equal(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"service TestApi",
				"{",
				"}",
				"",
			});
		}

		[Test]
		public void BlankServiceDefinition()
		{
			TestUtility.ParseInvalidTestApi("").Message.Should().Be("TestApi.fsd(1,1): expected '[' or 'service'");
		}

		[Test]
		public void WhitespaceServiceDefinition()
		{
			TestUtility.ParseInvalidTestApi(" \r\n\t ").Message.Should().Be("TestApi.fsd(2,3): expected '[' or 'service'");
		}

		[Test]
		public void MissingServiceName()
		{
			TestUtility.ParseInvalidTestApi("service{}").Message.Should().Be("TestApi.fsd(1,8): expected service name");
		}

		[Test]
		public void MissingServiceBody()
		{
			TestUtility.ParseInvalidTestApi("service TestApi").Message.Should().Be("TestApi.fsd(1,16): expected '{'");
		}

		[Test]
		public void MissingEndBrace()
		{
			TestUtility.ParseInvalidTestApi("service TestApi {").Message.Should().Be("TestApi.fsd(1,18): expected '}' or '[' or 'data' or 'enum' or 'errors' or 'method'");
		}

		[Test]
		public void DuplicatedService()
		{
			TestUtility.ParseInvalidTestApi("service TestApi{} service TestApi{}").Message.Should().Be("TestApi.fsd(1,19): expected end");
		}

		[Test]
		public void ServiceSummary()
		{
			var service = TestUtility.ParseTestApi("/// test\n/// summary\nservice TestApi{}");

			service.Summary.Should().Be("test summary");

			TestUtility.GenerateFsd(service).Should().Equal(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"/// test summary",
				"service TestApi",
				"{",
				"}",
				"",
			});
		}

		[Test]
		public void ServiceRemarks()
		{
			var service = TestUtility.ParseTestApi("service TestApi{}\n# TestApi\ntest\nremarks");

			service.Remarks[1].Should().Be("remarks");

			TestUtility.GenerateFsd(service).Should().Equal(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"service TestApi",
				"{",
				"}",
				"",
				"# TestApi",
				"",
				"test",
				"remarks",
				"",
			});
		}

		[Test]
		public void MethodRemarks()
		{
			var service = TestUtility.ParseTestApi("service TestApi { method do {}: {} }\n# do\nremarks");

			service.Methods.Single().Remarks.Single().Should().Be("remarks");

			TestUtility.GenerateFsd(service).Should().Equal(new[]
			{
				"// DO NOT EDIT: generated by TestUtility",
				"",
				"service TestApi",
				"{",
				"\tmethod do",
				"\t{",
				"\t}:",
				"\t{",
				"\t}",
				"}",
				"",
				"# do",
				"",
				"remarks",
				"",
			});
		}

		[Test]
		public void DuplicatedRemarks()
		{
			TestUtility.ParseInvalidTestApi("service TestApi { method do {}: {} }\n# do\nremarks\n# do\nremarks")
				.Message.Should().Be("TestApi.fsd(4,1): Duplicate remarks heading: do");
		}

		[Test]
		public void UnmatchedRemarks()
		{
			TestUtility.ParseInvalidTestApi("service TestApi{}\n# TestApi2\ntest\nremarks")
				.Message.Should().Be("TestApi.fsd(2,1): Unused remarks heading: TestApi2");
		}

		[Test]
		public void MultipleErrors()
		{
			TestUtility.TryParseInvalidTestApi("service TestApi { method do {}: {} data MyDto { x: InvalidData; } data One {} data One {} }\n# do\nremarks\n# do\nremarks\n# TestApi2\ntest\nremarks")
				.Count.Should().Be(4);
		}
	}
}
