name: Publish Docs

on:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

defaults:
  run:
    shell: pwsh

jobs:
  publish-docs:
    runs-on: windows-latest
    steps:
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required to publish docs
    - name: Publish Docs
      env:
        BUILD_BOT_PASSWORD: ${{ secrets.BUILD_BOT_PASSWORD }}
      run: .\build.ps1 publish --no-test --trigger publish-docs
